title: The Sorry Scheme of Things Entire
name: The Sorry Scheme of Things Entire
description: >- # this means to ignore newlines until "baseurl:"
  Dissatisfaction with the state of the art
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://thinwoodsman.github.io" 
author: Thin-Woodsman
github_username:  thinwoodsman

permalink: /:title/
include: [_pages]

markdown: kramdown
mathjax: true
highlighter: rouge
paginate: 7
paginate_path: "/:num/"
#date_format: "%b %-d, %Y"
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  syntax_highlighter: rouge
  math_engine: mathjax

defaults:
  -
    scope:
      type: posts
      path: _posts
    values:
      is_post: true
      layout: post
      category: misc
      permalink: /posts/:categories/:title/
  -
    scope:
      type: pages
      path: _pages
    values:
      is_post: false
      layout: default
      #permalink: /:title/

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap


# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
