title: The Sorry Scheme of Things Entire
#email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Dissatisfaction with the state of the art
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://thinwoodsman.github.io" 
#twitter_username: n/a
github_username:  thinwoodsman

permalink: /:title/
#markdown: kramdown
paginate: 7
paginate_path: "/:num/"
#date_format: "%b %-d, %Y"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap


# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
